[project]
site_name = "flagd-ui"
language = "en"
site_url = "https://danielhabenicht.github.io/flagd-ui/"
repo_url = "https://github.com/DanielHabenicht/flagd-ui"

[project.theme]
features = ["search.highlight", "navigation.footer"]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/DanielHabenicht/flagd-ui"
